<MainPage>:
    MDBoxLayout:
        size_hint: 1, None
        height: self.minimum_height
        padding: '5dp'

        orientation: "vertical"
        MDIconButton:
            icon: 'plus'

        MDLabel:
            text: 'Instagram'
            halign: 'center'
            valign: 'top'
            font_size: 25
            #font_name: 'libs/assets/Instafont.otf'

        MDIconButton:
            icon: 'facebook-messenger'
        ScrollView: