#:import Factory kivy.factory.Factory
<MyPopup@Popup>
    id: popik
    auto_dismiss: True
    title: ""

    size_hint: 0.6, 0.2
    pos_hit: {"x":0.5, "top": 0.5}
    Button:
        size_hint: 0.4, 1
        text: "Vyhledat na internetu"
        font_size: 24
        on_release: root.open_website(self)


<MainPage>

    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        Image:
            id: image
            size: root.width, root.height