MainPage:

<MainPage>:
    SecondPage:
    ThirdPage:

<SecondPage@BoxLayout>:
    orientation: "vertical"
    Label:
        size_hint: 1,0.05
        text: "My QR něco"
    MyImage:
        source: "images/1.jpg"
    AnchorLayout:
        size_hint: 1, 0.1
        pos_hint: {"bottom": 0.4}
        Button:

            size_hint: 0.8, 1
            anchor_y: "center"
            text: "lorem ipsum"
    Label:
        size_hint: 1,0.05
        text: ""



<ThirdPage@BoxLayout>:
    orientation: "vertical"
    MyImage:
        source: "images/6.jpg"
    Button:
        size: 10, 5
        text: "3"